### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by BKSalman** [BKSalman/sadmadbotlad#2]
- [ ] ~#4~
- [ ] Frontend 
    - [ ] #5
- [ ] feature: lurk command that shows some kind of effect on stream when used (something like [this](https://youtu.be/EGawuNhXHIc))
- [ ] feature: shout out overlay
- [ ] feature: ability to remove songs from the queue by index
- [ ] feature: stream sounds
- [ ] feature: slot machine channel points reward
- [ ] bug: #12

------------------------------

- Frontend
    - [x] #6
    - [x] Song queue
    - [x] Refresh token by getting the code
- [x] !قوانين (just need to add more)
- [x] !voteskip
- [x] fix not a valid URL panic
- [x] #9
- [x] #13
- [x] #10 (reimplementation)
